# Generated by Django 6.1.1 on 2026-09-22 23:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallet", "0003_transactionmodel_ledger_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("side", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(db_index=True, default="PENDING", max_length=20),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "filled_quantity",
                    models.DecimalField(
                        decimal_places=8, default="0.00000000", max_digits=18
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="wallet.walletmodel",
                    ),
                ),
            ],
            options={
                "db_table": "trading_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=18)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=18)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading.ordermodel",
                    ),
                ),
            ],
            options={
                "db_table": "trading_trades",
                "ordering": ["-executed_at"],
            },
        ),
    ]
