# Generated by Django 6.1.1 on 2026-09-24 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetmodel",
            options={
                "ordering": ["symbol"],
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.CreateModel(
            name="PriceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                ("value", models.DecimalField(decimal_places=8, max_digits=18)),
                ("recorded_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "db_table": "market_prices",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["asset_symbol", "-recorded_at"],
                        name="idx_price_symbol_time",
                    )
                ],
            },
        ),
    ]
