# Generated by Django 6.1.1 on 2026-09-24 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_transactionmodel_ledger_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAssetModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=8, default="0.00000000", max_digits=24
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_positions",
                        to="wallet.walletmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Asset",
                "verbose_name_plural": "Wallet Assets",
                "db_table": "wallet_assets",
                "ordering": ["asset_symbol"],
                "unique_together": {("wallet", "asset_symbol")},
            },
        ),
    ]
