# Generated by Django 6.1.1 on 2026-09-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_walletassetmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionmodel",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
