# Generated by Django 6.1.1 on 2026-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transactionmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='reference_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
